"""
optimize.py

Executes enterprise-grade hyperparameter optimization for the AI-Based 
Real-Time Fault Detection system.

Leveraging the Optuna framework and the Tree-structured Parzen Estimator (TPE), 
this module automates the discovery of optimal hyperparameter configurations 
for the multi-target classifiers generated by the ModelFactory.
"""

import json
import logging
import time
from pathlib import Path
from typing import Any, Callable, Dict, Optional, Union

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, cross_val_score
from sklearn.multioutput import MultiOutputClassifier

try:
    import optuna
    from optuna.samplers import TPESampler
    OPTUNA_AVAILABLE = True
except ImportError:
    OPTUNA_AVAILABLE = False

from .model_factory import FactoryConfig, ModelFactory, ModelCreationError


# Initialize module logger
logger = logging.getLogger(__name__)


class OptimizationError(Exception):
    """Exception raised for errors occurring during hyperparameter optimization."""
    pass


class HyperparameterOptimizer:
    """
    Automates hyperparameter tuning for multi-target machine learning models 
    using Bayesian optimization (Optuna).
    """

    TARGET_COLUMNS = ['sc_type', 'fault_target', 'phase_select']

    def __init__(self, factory: Optional[ModelFactory] = None) -> None:
        """
        Initializes the HyperparameterOptimizer.

        Args:
            factory (Optional[ModelFactory]): An injected instance of ModelFactory.
                If None, a new instance is created automatically.
        """
        if not OPTUNA_AVAILABLE:
            logger.error("Optuna is not installed.")
            raise OptimizationError(
                "The 'optuna' library is required for optimization. "
                "Please install it using 'pip install optuna'."
            )
            
        self.factory = factory or ModelFactory()

    def _prepare_data(self, data: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Validates column presence and separates features (X) from targets (y).

        Args:
            data (pd.DataFrame): The preprocessed dataset.

        Returns:
            Tuple[pd.DataFrame, pd.DataFrame]: A tuple containing X and y DataFrames.

        Raises:
            OptimizationError: If the dataset is missing target columns or features.
        """
        if data.empty:
            raise OptimizationError("Provided dataset for optimization is empty.")

        missing_targets = [col for col in self.TARGET_COLUMNS if col not in data.columns]
        if missing_targets:
            raise OptimizationError(f"Dataset missing required targets: {missing_targets}")

        y = data[self.TARGET_COLUMNS]
        X = data.drop(columns=self.TARGET_COLUMNS)

        if X.empty:
            raise OptimizationError("Dataset contains no features after dropping targets.")

        return X, y

    def _get_search_space(
        self, trial: optuna.Trial, model_name: str
    ) -> Dict[str, Any]:
        """
        Defines the continuous, discrete, and categorical hyperparameter search 
        spaces for each supported model architecture.

        Args:
            trial (optuna.Trial): The current Optuna trial object.
            model_name (str): The registered name of the model being optimized.

        Returns:
            Dict[str, Any]: A dictionary of suggested hyperparameters for the trial.

        Raises:
            OptimizationError: If the model_name is not configured for optimization.
        """
        params: Dict[str, Any] = {}

        if model_name == 'svm':
            params['C'] = trial.suggest_float('C', 1e-3, 1e3, log=True)
            params['kernel'] = trial.suggest_categorical('kernel', ['rbf', 'poly', 'sigmoid'])
            if params['kernel'] == 'poly':
                params['degree'] = trial.suggest_int('degree', 2, 5)
            params['gamma'] = trial.suggest_categorical('gamma', ['scale', 'auto'])

        elif model_name == 'random_forest':
            params['n_estimators'] = trial.suggest_int('n_estimators', 50, 500, step=50)
            params['max_depth'] = trial.suggest_int('max_depth', 5, 50)
            params['min_samples_split'] = trial.suggest_int('min_samples_split', 2, 20)
            params['min_samples_leaf'] = trial.suggest_int('min_samples_leaf', 1, 10)
            params['max_features'] = trial.suggest_categorical(
                'max_features', ['sqrt', 'log2', None]
            )

        elif model_name == 'xgboost':
            params['n_estimators'] = trial.suggest_int('n_estimators', 100, 1000, step=100)
            params['learning_rate'] = trial.suggest_float('learning_rate', 1e-3, 0.3, log=True)
            params['max_depth'] = trial.suggest_int('max_depth', 3, 12)
            params['subsample'] = trial.suggest_float('subsample', 0.5, 1.0)
            params['colsample_bytree'] = trial.suggest_float('colsample_bytree', 0.5, 1.0)
            params['gamma'] = trial.suggest_float('gamma', 0.0, 5.0)

        elif model_name == 'mlp':
            n_layers = trial.suggest_int('n_layers', 1, 3)
            layers = []
            for i in range(n_layers):
                layers.append(trial.suggest_int(f'n_units_l{i}', 16, 256, step=16))
            params['hidden_layer_sizes'] = tuple(layers)
            params['alpha'] = trial.suggest_float('alpha', 1e-5, 1e-1, log=True)
            params['learning_rate_init'] = trial.suggest_float(
                'learning_rate_init', 1e-4, 1e-1, log=True
            )
            params['activation'] = trial.suggest_categorical(
                'activation', ['relu', 'tanh', 'logistic']
            )

        else:
            raise OptimizationError(
                f"Hyperparameter search space not defined for model '{model_name}'."
            )

        return params

    def _create_objective(
        self, 
        model_name: str, 
        X: pd.DataFrame, 
        y: pd.DataFrame, 
        n_splits: int
    ) -> Callable[[optuna.Trial], float]:
        """
        Creates the objective function required by Optuna's study.

        Args:
            model_name (str): The model to optimize.
            X (pd.DataFrame): Features.
            y (pd.DataFrame): Targets.
            n_splits (int): Number of K-Fold splits for evaluation.

        Returns:
            Callable[[optuna.Trial], float]: The objective function.
        """
        def objective(trial: optuna.Trial) -> float:
            # 1. Generate trial hyperparameters
            trial_params = self._get_search_space(trial, model_name)
            
            # 2. Build configuration
            config = FactoryConfig(model_name=model_name, params=trial_params)
            
            # 3. Instantiate base model via factory
            try:
                base_model = self.factory.create(config)
            except ModelCreationError as e:
                logger.error(f"Failed to create model in trial: {e}")
                raise optuna.exceptions.TrialPruned() from e

            # 4. Wrap for multi-target classification
            multi_target_model = MultiOutputClassifier(base_model, n_jobs=-1)

            # 5. Cross-validate
            # In scikit-learn, multi-output 'accuracy' strictly requires exact matches 
            # across all targets simultaneously (Exact Match Ratio), matching our need.
            cv = KFold(n_splits=n_splits, shuffle=True, random_state=42)
            try:
                scores = cross_val_score(
                    estimator=multi_target_model,
                    X=X,
                    y=y,
                    cv=cv,
                    scoring='accuracy',
                    n_jobs=-1
                )
            except BaseException as e:
                logger.warning(f"Cross validation failed in trial. Pruning. Error: {e}")
                raise optuna.exceptions.TrialPruned() from e

            # Return the mean exact match ratio
            return float(np.mean(scores))

        return objective

    def optimize(
        self, 
        model_name: str, 
        train_data: pd.DataFrame, 
        n_trials: int = 50, 
        n_splits: int = 3,
        timeout_seconds: Optional[int] = None,
        output_dir: Optional[Union[str, Path]] = None
    ) -> FactoryConfig:
        """
        Executes the hyperparameter optimization study.

        Args:
            model_name (str): The registered name of the model to optimize.
            train_data (pd.DataFrame): The full training dataset.
            n_trials (int): Number of optimization trials to run.
            n_splits (int): Number of K-Fold cross-validation splits per trial.
            timeout_seconds (Optional[int]): Maximum time in seconds for the study.
            output_dir (Optional[Union[str, Path]]): Directory to save the trial results.

        Returns:
            FactoryConfig: A fully populated configuration object containing the 
                optimal hyperparameters discovered during the study.

        Raises:
            OptimizationError: If the study fails to execute or finds no valid trials.
        """
        logger.info(f"Starting Hyperparameter Optimization for '{model_name}'...")
        logger.info(f"Targeting {n_trials} trials with {n_splits}-fold CV.")

        if model_name not in self.factory.available_models():
            raise OptimizationError(f"Model '{model_name}' is not registered in the Factory.")

        X, y = self._prepare_data(train_data)
        
        # Configure Optuna study
        sampler = TPESampler(seed=42)
        study_name = f"{model_name}_optimization_{int(time.time())}"
        study = optuna.create_study(
            study_name=study_name,
            direction="maximize",
            sampler=sampler
        )

        objective = self._create_objective(model_name, X, y, n_splits)

        start_time = time.time()
        try:
            # Optuna logs at INFO level by default, which is highly verbose.
            # We wrap it in a cleaner try/except for robust pipeline execution.
            optuna.logging.set_verbosity(optuna.logging.WARNING)
            study.optimize(
                objective, 
                n_trials=n_trials, 
                timeout=timeout_seconds, 
                catch=(optuna.exceptions.TrialPruned,)
            )
        except Exception as e:
            logger.error(f"Optimization study failed unexpectedly: {e}")
            raise OptimizationError(f"Study execution failed: {e}") from e

        elapsed = time.time() - start_time
        
        if len(study.trials) == 0 or study.best_trial is None:
            raise OptimizationError("Optimization completed, but no successful trials were found.")

        best_params = study.best_trial.params
        best_score = study.best_value
        
        logger.info(
            f"Optimization finished in {elapsed:.2f} seconds. "
            f"Best Exact Match Ratio: {best_score:.4f}"
        )
        logger.info(f"Best hyperparameters: {best_params}")

        # Optionally persist study results for CI/CD tracking
        if output_dir:
            self._save_study_results(study, model_name, best_score, output_dir)

        # Return the optimal configuration ready for training
        return FactoryConfig(
            model_name=model_name,
            params=best_params
        )

    def _save_study_results(
        self, 
        study: optuna.Study, 
        model_name: str, 
        best_score: float, 
        output_dir: Union[str, Path]
    ) -> None:
        """
        Saves the best parameters and summary of the Optuna study to disk.

        Args:
            study (optuna.Study): The completed Optuna study.
            model_name (str): The name of the optimized model.
            best_score (float): The objective value of the best trial.
            output_dir (Union[str, Path]): Output directory path.
        """
        out_path = Path(output_dir)
        try:
            out_path.mkdir(parents=True, exist_ok=True)
            
            results = {
                "model_name": model_name,
                "best_exact_match_ratio": best_score,
                "best_params": study.best_trial.params,
                "total_trials": len(study.trials),
                "completed_trials": len([t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]),
                "pruned_trials": len([t for t in study.trials if t.state == optuna.trial.TrialState.PRUNED])
            }
            
            file_path = out_path / f"{model_name}_opt_results.json"
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(results, f, indent=4)
                
            logger.info(f"Saved optimization results to {file_path}")
            
        except Exception as e:
            logger.error(f"Failed to save optimization results: {e}")